# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e620fcd22c86a4aebb5ebd8ce739d4e90a31ec2144cbb43ca85d78f43491eb094cc3a4da5956fe9980b74426054efb9f57d242ba587e9f0ab60e6192f1090d4

test:
  secret_key_base: a2b8b6573eab270a0d2c96cb341a202ccd08cee0dc493ec1838c1a0594a8254c0f4d7eb77fd38caf424ba6d10577b823c6d5f012d119a184199cd6a6d10e4645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
